up:
  - python: 3.6.4
  - pipfile

commands:
  run:
    run: python -m cocorico

  push:
    run: pytest && ((git add cocorico fonts sounds && git add -u && git commit -m 'autopush'); git push resin)

  test:
    run: pytest -v tests
