up:
  - python: 3.6.4
  # - pip: [requirements.txt]

commands:
  run:
    run: GPIOZERO_PIN_FACTORY=mock python -m cocorico

  push:
    run: git add cocorico && git add -u && git commit -m 'autopush' && git push resin
