up:
  - python: 3.6.4
  - pip: [requirements.txt]

commands:
  run:
    run: python -m cocorico

  push:
    run: (git add cocorico fonts sounds && git add -u && git commit -m 'autopush'); git push resin
